apiVersion: apps/v1
kind: Deployment
metadata:
  name: statefulset-drain-controller
  namespace: kube-system
  labels:
    app: statefulset-drain-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statefulset-drain-controller
  template:
    metadata:
      labels:
        app: statefulset-drain-controller
    spec:
      serviceAccountName: statefulset-drain-controller
      containers:
      - name: main
        image: docker.io/luksa/statefulset-drain-controller:0.5
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: statefulset-drain-controller
  namespace: kube-system
  labels:
    app: statefulset-drain-controller
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: statefulset-drain-controller
  namespace: kube-system
  labels:
    app: statefulset-drain-controller
subjects:
  - kind: ServiceAccount
    name: statefulset-drain-controller
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: statefulset-drain-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: statefulset-drain-controller
  labels:
    app: statefulset-drain-controller
rules:
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
